name: CI

on:
  # run on all PRs for any branch, provides 'Checks' ux in PRs
  pull_request:
  # run on published releases, our build badge in README.md is based on this
  # replaces travis-ci's existing workflow/badge
  push:
    branches: [master]

jobs:
  unit-tests:
    name: Go unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - run: go version
    - run: go test -v .
